[package]
name = "nimbleparse_lsp"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.15"
thiserror = "1.0.30"
tokio = {version = "1.17.0", features=["fs", "macros", "rt-multi-thread", "io-std", "process"]}
tower-lsp = "0.16.0"
nimbleparse_toml = {path = "../toml"}
toml = {version = "0.5.8", features=["preserve_order"]}
serde-transcode = "1.1.1"
serde_json = { version = "1.0.79", features=["preserve_order"]}
cfgrammar = {git = "https://github.com/ratmice/grmtools", branch="rope_lexer"}
lrpar = {git = "https://github.com/ratmice/grmtools/", branch="rope_lexer"}
lrlex = {git = "https://github.com/ratmice/grmtools/", branch="rope_lexer", features=["rope"]}
lrtable = {git = "https://github.com/ratmice/grmtools/", branch="rope_lexer"}
num-traits = "0.2.14"
tokio-stream = "0.1.8"
ropey = "1.4.1"

[dependencies.console-subscriber]
version = "0.1.4"
optional = true

[features]
default = []
console = ["console-subscriber"]
